### ISSUE TITLE
File Name Warning is Broken

### ISSUE THREAD

**Issue by langstonzac25** [PrettyBoyCosmo/ProtocolBlue#1]
![image](https://github.com/PrettyBoyCosmo/ProtocolBlue/assets/101570030/f4ff9209-bd62-4981-81e6-d20043b6daeb)

When you try to name your note something tht has been already used there is a warning but it is broken. Here is what it should look like

![image](https://github.com/PrettyBoyCosmo/ProtocolBlue/assets/101570030/d9c89276-d73a-47f8-8413-d572ab70613d)

I have tried researching this problem but have not found anything yet. I try looking into it a little soon.

**Comment by PrettyBoyCosmo** [comment]
**fixed it! thanks for lettin me kno :)**


![2023-05-18_12-30_1](https://github.com/PrettyBoyCosmo/ProtocolBlue/assets/73325248/26279423-8c96-4550-8ec8-06f342d75039)
![2023-05-18_12-30](https://github.com/PrettyBoyCosmo/ProtocolBlue/assets/73325248/daab887f-1e0f-4166-b23e-045762a92ea2)
